#!/bin/bash

# This actually needs to be a script that runs remotely using SSH so that we can also copy across the bosh_environment file to AWS

if [ ! -d ~/workspace ]; then
  mkdir -p ~/workspace
fi

echo "install: --no-ri --no-rdoc
update:  --no-ri --no-rdoc
" >~/.gemrc

sudo apt-get -y install ruby ruby-dev make libxml2-dev libxslt-dev g++ mysql-client libmysqlclient-dev postgresql-server-dev-9.3 libsqlite3-dev build-essential make
sudo apt-get update

sudo apt-get install unzip


# Install Chruby version 1.9.3-p547 using RVM or RBENV package managers
wget -O chruby-0.3.8.tar.gz https://github.com/postmodern/chruby/archive/v0.3.8.tar.gz
tar -xzvf chruby-0.3.8.tar.gz
cd chruby-0.3.8/
sudo make install

# Setup chruby Ruby etc
sudo ./scripts/setup.sh
cd ..
#add to ~/.bashrc
echo "source /usr/local/share/chruby/chruby.sh" >> ~/.bashrc
echo "chruby 1.9.3" >> ~/.bashrc

ruby-install ruby 1.9.3

#and run at command line
source /usr/local/share/chruby/chruby.sh

chruby 1.9.3
chruby #check that you have ruby 1.9.3

sudo gem install nokogiri -- --use-system-libraries --with-xml2-include=/usr/include/libxml2 
sudo gem install bundler

sudo gem install -V bosh_cli
sudo gem install -V bosh_cli_plugin_micro
sudo gem install -V bosh_cli_plugin_aws


#Install Spiff
cd ~/workspace
wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.3/spiff_linux_amd64.zip
unzip spiff_linux_amd64.zip
sudo mv spiff /usr/local/bin
rm spiff_linux_amd64.zip

#Install CF CLI
wget "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github"
mv "stable?release=linux64-binary&source=github" cli.tar.gz
tar -zxvf cli.tar.gz
sudo mv cf /usr/local/bin
