#!/bin/bash

# This actually needs to be a script that runs remotely using SSH so that we can also copy across the bosh_environment file to AWS

if [ ! -d ~/workspace ]; then
  mkdir -p ~/workspace
fi

echo "install: --no-ri --no-rdoc
update:  --no-ri --no-rdoc
" >~/.gemrc

sudo apt-get update
sudo apt-get -y install ruby ruby-dev make libxml2-dev libxslt-dev g++ mysql-client libmysqlclient-dev postgresql-server-dev-9.3 libsqlite3-dev build-essential 
sudo apt-get -y install make
sudo apt-get -y install unzip


sudo gem install nokogiri -- --use-system-libraries --with-xml2-include=/usr/include/libxml2 
sudo gem install bundler

sudo gem install -V bosh_cli
sudo gem install -V bosh_cli_plugin_micro
sudo gem install -V bosh_cli_plugin_aws


#Install Spiff
cd ~/workspace
wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.3/spiff_linux_amd64.zip
unzip spiff_linux_amd64.zip
sudo mv spiff /usr/local/bin
rm spiff_linux_amd64.zip

#Install CF CLI
wget "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github"
mv "stable?release=linux64-binary&source=github" cli.tar.gz
tar -zxvf cli.tar.gz
sudo mv cf /usr/local/bin

#install the silver Searcher
apt-get install silversearcher-ag
