#!/bin/bash

# This actually needs to be a script that runs remotely using SSH so that we can also copy across the bosh_environment file to AWS

if [ ! -d ~/workspace ]; then
  mkdir -p ~/workspace
fi

echo "install: --no-ri --no-rdoc
update:  --no-ri --no-rdoc
" >~/.gemrc

sudo yum groupinstall 'Development Tools'
sudo yum install -y git gcc ruby-devel libxml2 libxml2-devel libxslt libxslt-devel postgresql postgresql-devel mysql-server mysql-devel sqlite-devel golang gcc-c++

# Install Chruby version 1.9.3-p547 using RVM or RBENV package managers
wget -O chruby-0.3.8.tar.gz https://github.com/postmodern/chruby/archive/v0.3.8.tar.gz
tar -xzvf chruby-0.3.8.tar.gz
cd chruby-0.3.8/
sudo make install

# Setup chruby Ruby etc
sudo ./scripts/setup.sh
cd ..
#add to ~/.bashrc
source /usr/local/share/chruby/chruby.sh


ruby-install ruby 1.9.3

#and run at command line
source /usr/local/share/chruby/chruby.sh

chruby 1.9.3
chruby #check that you have ruby 1.9.3

gem install nokogiri -- --use-system-libraries
gem install bundler

cd ~/workspace
git clone git@github.com:pivotalservices/bosh.git # This is to get around the pull request issue shown later.
cd ~/workspace/bosh
bundle install

#Install Spiff
cd ~/workspace
wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.3/spiff_linux_amd64.zip
unzip spiff_linux_amd64.zip
sudo mv spiff /usr/local/bin
rm spiff_linux_amd64.zip
